env: "testing"
application_name: upassed-account-service
storage:
    host: "localhost"
    port: "5432"
    database_name: "upassed-account-service-db"
    user: "user"
    password: "password"
grpc_server:
    port: "44044"
    timeout: 10m
migrations:
    migrations_path: "../../../migration/scripts"
    migrations_table_name: "migrations"
timeouts:
    endpoint_execution_timeout_ms: 40000
tracing:
    host: localhost
    port: 4317
    credentials_tracer_name: credentials-tracer
redis:
    user: default
    password: password
    host: localhost
    port: 6379
    database_number: 0
    entity_ttl: 5m
rabbit:
    user: upassed-rabbit-user
    password: upassed-rabbit-password
    host: localhost
    port: 5672
    exchange:
        name: upassed-authentication-service
        type: direct
    queues:
        credentials_create:
            name: credentials-create-queue
            routing_key: credentials.create
