env: "testing"
storage:
    host: "localhost"
    port: "5432"
    database_name: "upassed-account-service-db"
    user: "user"
    password: "password"
grpc_server:
    port: "44044"
    timeout: 10m
migrations:
    migrations_path: "../../../migration/scripts"
    migrations_table_name: "migrations"
